/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 tree2.glb --transform 
Files: tree2.glb [93.87KB] > /Users/inbeom/dev/devWeb/concretecake/src/assets/models/tree2-transformed.glb [11.68KB] (88%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import model from "Assets/models/tree2-transformed.glb";

export function Tree2(props) {
  const { nodes, materials } = useGLTF(model);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.wood001.geometry}
        material={materials.treeWood2}
        position={[0, -0.075, 0]}
        scale={[0.203, 0.414, 0.203]}
        castShadow
      />
      <mesh
        geometry={nodes.Sphere018.geometry}
        material={materials.treeLeaf}
        position={[0, 1.141, 0]}
        scale={0.874}
        castShadow
      />
    </group>
  );
}

useGLTF.preload(model);
