/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 beehive.glb --transform 
Files: beehive.glb [203.47KB] > /Users/inbeom/dev/devWeb/concretecake/src/assets/models/beehive-transformed.glb [28.92KB] (86%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/beehive-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere039.geometry} material={materials.beehive1} position={[0, 0.032, 0]} scale={[1.107, 0.479, 1.107]} />
      <mesh geometry={nodes.Torus013.geometry} material={materials.heehive2} position={[0, 1.654, 0]} scale={[0.953, 1, 0.953]} />
      <mesh geometry={nodes.Cylinder039.geometry} material={materials['heehive hole']} position={[0.94, 0.856, -0.932]} rotation={[Math.PI / 2, 0, -2.346]} scale={[0.145, 0.28, 0.145]} />
      <mesh geometry={nodes.branch001.geometry} material={materials.treeWood} position={[-1.863, 3.093, 0]} rotation={[0, 0, -1.351]} scale={0.145} />
    </group>
  )
}

useGLTF.preload('/beehive-transformed.glb')
